server:
  port: 6820
  servlet:
    session:
      timeout: 72h
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
  #postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres}
    username: ${POSTGRES_USERNAME:postgres.cpmbiildtwwdramvyeaf}
    password: ${POSTGRES_PASSWORD:ngocthe@6820}

    #connection pool
    hikari:
      pool-name: AppHikariCP
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      auto-commit: true
      validation-timeout: 5000
      connection-test-query: SELECT 1

  #jpa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        type: trace
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  #redis
  data:
    redis:
      host: localhost
      port: 6379
      password: root

  #session
  session:
    redis:
      namespace: custom:session
      flush-mode: immediate
    timeout: 72h

  #messages
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600

  #thymeleaf
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    cache: false

logging:
  config: classpath:logs/logback-spring.xml
  level:
    org:
      springframework:
        web: INFO

#variables
jwt:
  signer_key: ${JWT_SIGNER_KEY:gv39I0MSQOp75qfmT7fdR+YmJPenVOfhOZg07HtQJ0zv/mhUv5mnlf+dyhEvEpJZ}

mail:
  username: ${MAIL_USERNAME:ngocthe.affiliate@gmail.com}
  password: ${MAIL_PASSWORD:xgsofpbrlhacsvsx}

homepage:
  url: ${HOMEPAGE_URL:http://localhost:6820}

aws:
  s3:
    bucket-name: ngow-shop
    region: ap-southeast-1
    access-key: ${AWS_ACCESS_KEY_ID:889d22f5ec8f9ae71379d69eb2a8eb88}
    secret-key: ${AWS_SECRET_ACCESS_KEY:7dd348498a4722f126bf6b8e6c7c00f0253ea9ffcf6099fe01b290883a0fb7f7}
    cdn-url: https://cpmbiildtwwdramvyeaf.storage.supabase.co/storage/v1/s3
    public-url: https://cpmbiildtwwdramvyeaf.supabase.co/storage/v1/object/public
