server:
  port: 6820

spring:
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/custom
    username: root
    password: root
    #connection pool
    hikari:
      pool-name: AppHikariCP
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      auto-commit: true
      validation-timeout: 5000
      connection-test-query: SELECT 1
  #jpa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type: trace

logging:
  level:
    org:
      springframework:
        web: INFO

#variables
jwt:
  signer_key: gv39I0MSQOp75qfmT7fdR+YmJPenVOfhOZg07HtQJ0zv/mhUv5mnlf+dyhEvEpJZ

mail:
  username: ngocthe.affiliate@gmail.com
  password: xgsofpbrlhacsvsx
