server:
  port: 6820

spring:
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:33066/custom}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

    #connection pool
    hikari:
      pool-name: AppHikariCP
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      auto-commit: true
      validation-timeout: 5000
      connection-test-query: SELECT 1
  #jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        type: trace

  #servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    org:
      springframework:
        web: INFO

#variables
jwt:
  signer_key: ${JWT_SIGNER_KEY:gv39I0MSQOp75qfmT7fdR+YmJPenVOfhOZg07HtQJ0zv/mhUv5mnlf+dyhEvEpJZ}

mail:
  username: ${MAIL_USERNAME:ngocthe.affiliate@gmail.com}
  password: ${MAIL_PASSWORD:xgsofpbrlhacsvsx}

frontend:
  url: ${FRONTEND_URL:http://localhost:6820}
  verify_account_path: ${FRONTEND_VERIFY_PATH:/auth/active}

media:
  image-upload-dir: ./uploads/images
  video-upload-dir: ./uploads/videos
