server:
  port: 6820

spring:
  #mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

    #connection pool
    hikari:
      pool-name: AppHikariCP
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      auto-commit: true
      validation-timeout: 5000
      connection-test-query: SELECT 1

  #jpa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type: trace

#variables
jwt:
  signer_key: ${JWT_SIGNER_KEY}

mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

frontend:
  url: ${FRONTEND_URL}
  verify_account_path: ${FRONTEND_VERIFY_PATH}

media:
  image-upload-dir: ./uploads/images
  video-upload-dir: ./uploads/videos
