server:
  port: 6820

spring:
  #postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

    #connection pool
    hikari:
      pool-name: AppHikariCP
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      auto-commit: true
      validation-timeout: 5000
      connection-test-query: SELECT 1

  #jpa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        type: trace
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  config: classpath:logs/logback-spring.xml
  level:
    org:
      springframework:
        web: INFO

#variables
jwt:
  signer_key: ${JWT_SIGNER_KEY}

mail:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

frontend:
  url: ${FRONTEND_URL}
  verify_account_path: ${FRONTEND_VERIFY_PATH}

media:
  image-upload-dir: ./uploads/images
  video-upload-dir: ./uploads/videos
