server:
  port: 6820

spring:
  #postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:54321/custom}
    username: ${POSTGRES_USERNAME:custom}
    password: ${POSTGRES_PASSWORD:custom}

    #connection pool
    hikari:
      pool-name: AppHikariCP
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      auto-commit: true
      validation-timeout: 5000
      connection-test-query: SELECT 1

  #jpa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        type: trace
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  config: classpath:logs/logback-spring.xml
  level:
    org:
      springframework:
        web: INFO

#variables
jwt:
  signer_key: ${JWT_SIGNER_KEY:gv39I0MSQOp75qfmT7fdR+YmJPenVOfhOZg07HtQJ0zv/mhUv5mnlf+dyhEvEpJZ}

mail:
  username: ${MAIL_USERNAME:ngocthe.affiliate@gmail.com}
  password: ${MAIL_PASSWORD:xgsofpbrlhacsvsx}

frontend:
  url: ${FRONTEND_URL:http://localhost:6820}
  verify_account_path: ${FRONTEND_VERIFY_PATH:/auth/active}

media:
  image-upload-dir: ./uploads/images
  video-upload-dir: ./uploads/videos

aws:
  s3:
    bucket-name: ngow-shop
    region: ap-southeast-1
    access-key: ${AWS_ACCESS_KEY_ID:9f56ead5a1159fc16a112a73189846ee}
    secret-key: ${AWS_SECRET_ACCESS_KEY:5343bb96bb241fe9eb936cd218f5fce64d96c279aa8ccef58496365f2c3eac54}
    image-folder: uploads/images/
    video-folder: uploads/videos/
    cdn-url: https://cpmbiildtwwdramvyeaf.supabase.co/storage/v1/s3
